name: wallhaven_api
description: Wallhaven API wrapper for the Dart programming language.
version: 0.1.0
repository: https://github.com/rozpo/wallhaven_api

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
